[package]
name = "chriscerie/react-redux"
description = ""
version = "0.1.0"
license = "MIT"
authors = ["Dan Abramov", "Meta Platforms, Inc"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
TestEZ = "roblox/testez@^0.4"
React ="core-packages/react@17.0.1-rc.16"
ReactRoblox = "core-packages/react-roblox@17.0.1-rc.16"
Redux = "roblox/rodux@*"
Shared = "core-packages/shared@17.0.1-rc.16"
LuauPolyfill = "core-packages/luau-polyfill@^1.1"
Collections = "core-packages/collections@^1.1"
